rpg/apps/accounts/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import include, path, reverse
from django.views.generic.base import RedirectView
from .views import SignUp

app_name = 'accounts'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('signup/', SignUp.as_view(), name='signup'),
    path('login/success/', RedirectView.as_view(pattern_name='characters'), name='login_success'),
]

rpg/apps/creator/urls.py
from django.urls import path

from . import views

app_name = 'creator'
urlpatterns = [
    path('create/', views.CharacterCreateView.as_view(), name='create'),
    path('update/', views.CharacterUpdateView.as_view(), name='update'),
]

rpg/apps/dice/urls.py
from django.urls import path
from . import views


app_name = 'dice'
urlpatterns = [
    path('ajax/roll_stats/', views.rolled_stats, name='roll_stats'),
]

rpg/rpg/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from . import views


app_urls = [
    path('accounts/', include('apps.accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls, name='admin'),
    path('creator/', include('apps.creator.urls', namespace='creator')),
    path('dice/', include('apps.dice.urls', namespace='dice')),
]


urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('characters/', views.CharactersView.as_view(), name='characters'),
] + app_urls

rpg/apps/accounts/models.py
from django.db import models

rpg/apps/creator/models.py
from django.contrib.postgres.fields import JSONField, ArrayField
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Classes(models.Model):
    class_name = models.CharField(db_column='class', unique=True, max_length=16)
    hit_die = models.PositiveSmallIntegerField()
    skill_points = models.PositiveSmallIntegerField()
    class_skills = ArrayField(models.CharField(max_length=32))
    alignments = ArrayField(models.CharField(max_length=16))
    armor_proficiencies = ArrayField(models.CharField(max_length=16))
    weapon_proficiencies = ArrayField(models.CharField(max_length=16))
    spell_caster = models.BooleanField()


class Levels(models.Model):
    level = models.PositiveSmallIntegerField()
    class_name = models.ForeignKey(Classes, to_field='class_name', db_column='class', on_delete=models.PROTECT)
    level_info = JSONField()


class Races(models.Model):
    race = models.CharField(unique=True, max_length=16)
    # TODO: can't be foreign key since Human='All', how to handle?
    #favored_class = models.ForeignKey(Classes, to_field='class_name', on_delete=models.PROTECT)
    favored_class = models.CharField(max_length=16)
    size = models.CharField(max_length=10)
    speed = models.PositiveSmallIntegerField()
    race_info = JSONField()
    feats = ArrayField(models.CharField(max_length=64))
    languages = ArrayField(models.CharField(max_length=16))
    traits = ArrayField(models.CharField(max_length=64))
    special_abilities = ArrayField(models.CharField(max_length=64))
    ability_modifier = JSONField()


class Characters(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    name = models.CharField(max_length=48)
    character_class = models.ForeignKey(Classes, to_field='class_name', on_delete=models.PROTECT)
    character_race = models.ForeignKey(Races, to_field='race', on_delete=models.PROTECT)
    level = models.ForeignKey(Levels, on_delete=models.PROTECT)
    character_info = JSONField()

rpg/apps/dice/models.py
from django.db import models

# Create your models here.

rpg/apps/accounts/forms.py
from django import forms

rpg/apps/creator/forms.py
from django import forms
from .models import Characters, Classes, Levels, Races


class ClassModelChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.class_name


class RaceModelChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.race


class LevelModelChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.level


class CharacterForm(forms.ModelForm):
    character_class = ClassModelChoiceField(queryset=Classes.objects.all(), empty_label=None)
    character_race = RaceModelChoiceField(queryset=Races.objects.all(), empty_label=None)
    level = forms.IntegerField(min_value=1, max_value=20, initial=1, disabled=True)
    abil_strength        = forms.IntegerField(label='STR', initial=8)
    abil_dexterity       = forms.IntegerField(label='DEX', initial=8)
    abil_constitution    = forms.IntegerField(label='CON', initial=8)
    abil_intelligence    = forms.IntegerField(label='INT', initial=8)
    abil_wisdom          = forms.IntegerField(label='WIS', initial=8)
    abil_charisma        = forms.IntegerField(label='CHA', initial=8)
    scores = forms.CharField(label='Ability Scores', initial="8, 10, 12, 13, 14, 15")

    class Meta:
        model = Characters
        exclude = ['user', 'character_info']
        widgets = {
            'scores': forms.TextInput(attrs={'readonly': 'True'})
        }

rpg/apps/accounts/views.py
from django.shortcuts import HttpResponseRedirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import redirect
from django.views import generic


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    template_name = 'accounts/signup.html'

    def form_valid(self, form):
        form.save()
        username = self.request.POST['username']
        password = self.request.POST['password1']
        user = authenticate(self.request, username=username, password=password)
        if user is not None:
            login(self.request, user)

        return redirect('characters')

rpg/apps/creator/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views import View
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy

from .forms import CharacterForm
from .models import Characters


class CharacterCreateView(CreateView):
    form_class = CharacterForm
    template_name = 'creator/create.html'
    context_object_name = 'char_list'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class CharacterUpdateView(UpdateView):
    form_class = CharacterForm


class CharacterDeleteView(DeleteView):
    form_class = CharacterForm

rpg/apps/dice/views.py
from django.http import JsonResponse
from django.shortcuts import render
from .common import roll_stats


def rolled_stats(request):
    return JsonResponse({'stats': roll_stats()})

rpg/rpg/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import redirect, render
from django.views import generic

from apps.creator.models import Characters


class HomeView(generic.TemplateView):
    template_name = 'rpg/home.html'


class CharactersView(LoginRequiredMixin, generic.ListView):
    model = Characters
    template_name = 'rpg/characters.html'
    paginate_by = 10
    context_object_name = 'characters'

    def get_queryset(self):
        return Characters.objects.filter(user=self.request.user).order_by('name')

rpg/apps/accounts/templates/accounts/sign_up.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Sign Up</button>
  </form>
{% endblock %}

rpg/apps/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Sign Up</button>
    <a class="btn btn-secondary float-right" href="{% url 'accounts:login' %}">Sign In</a>
  </form>
{% endblock %}

rpg/apps/creator/templates/creator/character_form.html
{% extends "base.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_p }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

rpg/apps/creator/templates/creator/create.html
{% extends "base.html" %}
{% load static %}

{% block extend_head %}
  <link rel="stylesheet" href="{% static 'creator/css/style.css' %}">
{% endblock %}

{% block scripts %}
  <script>
    $(document).ready(function () {
      $("#roll").click(function() {
          $.get("{% url 'dice:roll_stats' %}", function(data) {
              $("label[for='id_scores']").text('Ability Scores:');
              $("input[name=scores]").val(data.stats.join(', '));
          }, "json");
      });

      $("#point").click(function() {
          $("label[for='id_scores']").text('Ability Points:');
          $("input[name=scores]").val(25);
      });

      $('label[id^="content_"]').hide();

    });
  </script>
{% endblock %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form }}
    </table>
    <br>
    <button id='manual' type="button" class="btn btn-secondary">Manual</button>
    <button id='point' type="button" class="btn btn-secondary">Point-Buy</button>
    <button id='roll' type="button" class="btn btn-secondary">Roll</button>
    <br><br>
    <button type="submit" class="btn btn-primary">Next</button>
  </form>
{% endblock %}

rpg/apps/creator/templates/creator/main.html
{% extends "base.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

rpg/rpg/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/4.1.1/css/bootstrap.min.css">
  <title>{% block title %}Character Creator{% endblock %}</title>
  {% block extend_head %}{% endblock %}
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">CC</a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
      {% with url_name=request.resolver_match.url_name %}
          <li class="nav-item {% if url_name == 'home' %}active{% endif %}">
            <a class="nav-link" href="{% url 'home' %}">Home</span></a>
          </li>
          <li class="nav-item {% if url_name == 'characters' %}active{% endif %}">
          {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'characters' %}">Characters</a>
          </li>
          {% endif %}
        {% endwith %}
      </ul>
      {% if user.is_authenticated %}
        <a class="nav-link"  href="{% url 'accounts:logout' %}">Log Out</a>
      {% else %}
        <a class="nav-link" href="{% url 'accounts:login' %}">Sign In</a>
        <a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>
      {% endif %}
    </div>
  </nav>

  <div class="container mt-3">
    {% block content %}{% endblock %}
  </div>

  <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.5.0.min.js"></script>
  <script src="https://ajax.aspnetcdn.com/ajax/jquery.ui/1.12.1/jquery-ui.min.js"></script>
  <script>
    (window.jQuery) || document.write("<script src=\"{% static 'rpg/scripts/jquery-3.5.0.min.js' %}\"><\/script>");
  </script>
  <script type="text/javascript">
    (!!window.jQuery.ui && !!window.jQuery.ui.version) || document.write("<script src=\"{% static 'rpg/scripts/jquery-ui-1.12.1.min.js' %}\"><\/script>");
  </script>
  <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/4.1.1/bootstrap.bundle.js"></script>

  {% block scripts %}{% endblock %}

</body>
</html>

rpg/rpg/templates/rpg/characters.html
{% extends "base.html" %}

{% block content %}
    <h1>Characters</h1>

    <p>Characters for {{ user.username }} </p>
    {% if characters %}
    <ul>
      {% for character in characters %}
      <li>
        <p>{{ character.name }}</p>
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>No characters created.</p>
    {% endif %}

    <a href="{% url 'creator:create' %}">Create Character</a>
{% endblock %}

rpg/rpg/templates/rpg/home.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<h1>Character Creator</h1>
  <p>
    {% if user.is_authenticated %}
      Welcome, {{ user.username }}
    {% else %}
      Welcome!
        <a class="btn btn-primary" href="{% url 'accounts:login' %}">Sign In</a>
        <a class="btn btn-primary" href="{% url 'accounts:signup' %}">Sign Up</a>
    {% endif %}
  </p>
{% endblock %}

rpg/rpg/templates/rpg/profile.html
{% extends "base.html" %}

{% block content %}
    <h1>Characters</h1>

    <p>Characters for {{ user.username }} </p>
    {% if characters %}

    <ul>

      {% for character in characters %}
      <li>
        <!--
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})
        -->
        <p>{{ character.name }}</p>
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>No characters created.</p>
    {% endif %}

    <a href="{% url 'creator:create' %}">Create Character</a>
    <p><a href="{% url 'accounts:logout' %}">logout</a></p>
{% endblock %}